const menu = [
    {
      id: 1,
      title: 'Sema Decor',
      category: 'React',      
      img: 'https://i.ibb.co/yYkbs8t/Capture.png',
      desc: `A responsive dynamic Rect App That Contains different pages, nested routes and modern design`,
      technologies: ['React', 'Context API', 'React Router V6', 'SASS', 'DaisyUI', 'Firebase' , ],
      url: 'https://sema-decor-zaqatala.netlify.app',
    },
    {
      id: 2,
      title: 'Comfy Sloth',
      category: 'React',
      img: 'https://i.ibb.co/tDgLkvZ/comfy-Sloth1.png',
      desc: `A furniture selling website has a shop page containing all sorts of filters made by reducers to keep one truth for state changes`,
      technologies:['React', 'Hooks', 'JS', 'Context API', 'Styled Components','React Router V6'],
    },
    {
      id: 3,
      title: 'Bankist',
      category: 'Vanilla JS',    
      img: 'https://i.ibb.co/6YFFzDJ/Bankist1.png',
      desc: `a functional programming paragdim project, allows money transfers, requesting loans and close accounts.
             user:ag pin:1111 or user:an pin: 2222`,
      technologies:['Vanilla JS', 'HTML5', 'CSS3'],
      url: 'https://bankist-app-agdev.netlify.app/',
    },
    {
      id: 4,
      title: 'country delight',
      category: 'HTML/CSS/JS',
      price: 20.99,
      img: './images/item-4.jpeg',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 5,
      title: 'egg attack',
      category: 'React',
      price: 22.99,
      img: './images/item-5.jpeg',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 6,
      title: 'Github API',
      category: 'React/API',
      img: 'https://i.ibb.co/ZY8p5W8/github-api.png',
      desc: `Calls the github api to display information like repos, followers, following, name, etc...,
      coded as a part of learning with coding addict and i used the same API to display my repos down ⬇`,
      technologies: ['React', 'Context API', 'Github API', 'Hooks'],
      url: 'https://react-github-api-ag.netlify.app/',
    },
    {
      id: 7,
      title: 'Old Portfolio',
      category: 'HTML/CSS/JS',
      price: 8.99,
      img: './images/item-7.jpeg',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      title: 'Nexter React',
      category: 'React',
      img: 'https://i.ibb.co/87wnnj7/nexter1.png',
      desc: `a beautifully designed website using CSS grids and remastered with react reusable components`,
      technologies: ['React', 'SASS'],
      url: 'https://nexter-react-version.netlify.app/'
    },
    {
      id: 9,
      title: 'Movies Finder',
      category: 'React/API',
      img: 'https://i.ibb.co/MG75ZTz/moviedb2.png',
      desc: `React App that calls the OMDB API to search movies and display results as movies are fetched from API and user types, 
      with react controlled query state`,
      technologies: ['React', 'Hooks' , 'Restful API', 'Context API'],
      url : 'https://movies-finder-agdev.netlify.app',
    },
  ];
  export default menu;
  